{{- range $.Values.app.workers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" $ }}-{{ .name }}
  labels:
    {{- include "laravel.labels" $ | nindent 4 }}
    laravel.com/pod-type: worker
    laravel.com/worker-name: {{ .name | quote }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" $ | nindent 6 }}
      laravel.com/pod-type: worker
      laravel.com/worker-name: {{ .name | quote }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel.selectorLabels" $ | nindent 8 }}
        laravel.com/pod-type: worker
        laravel.com/worker-name: {{ .name | quote }}
    spec:
      volumes:
        - name: env
          secret:
            secretName: {{ if $.Values.app.envSecretName }} {{ $.Values.app.envSecretName }} {{ else }} {{ $.Release.Name }}-env {{ end }}
        {{- with .extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "laravel.serviceAccountName" $ }}

      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}

      {{- with .extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- with .extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: worker
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ $.Values.app.image.repository }}:{{ $.Values.app.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.app.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - cp /tmp/.env /var/www/html/.env && cd /var/www/html && sh deploy.sh && {{ .command }}
          volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            {{- with .extraVolumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- with .extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
