apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: app
          emptyDir: {}
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        - name: nginx-config
          configMap:
            name: {{ if .Values.nginx.configName }} {{ .Values.nginx.configName }} {{ else }} {{ .Release.Name }}-nginx-config {{ end }}
        - name: php-ini-config
          configMap:
            name: {{ if .Values.phpIni.configName }} {{ .Values.phpIni.configName }} {{ else }} {{ .Release.Name }}-php-ini-config {{ end }}
        - name: php-fpm-config
          configMap:
            name: {{ if .Values.phpFpmConf.configName }} {{ .Values.phpFpmConf.configName }} {{ else }} {{ .Release.Name }}-php-fpm-config {{ end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "laravel.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: php-fpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: php-fpm-config
              mountPath: /usr/local/etc/php-fpm.d/laravel.conf
              subPath: laravel.conf
            {{- with .Values.app.extraVolumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp -r /app/. /var/www/html && cp /tmp/.env /var/www/html/.env && cd /var/www/html && sh deploy.sh
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- with .Values.nginx.extraVolumeMounts }}
            {{ toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
