{{- range .Values.app.workers }}
{{- if .autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "laravel.fullname" $ }}-{{ .name }}
  labels:
    {{- include "laravel.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ include "laravel.fullname" $ }}-{{ .name }}"
  minReplicas: {{ .autoscaling.minReplicas }}
  maxReplicas: {{ .autoscaling.maxReplicas }}
  maxReplicas: {{ .autoscaling.maxReplicas }}
  {{-  with .autoscaling.behavior }}
  behavior:
    {{ . toYaml | nindent 4 }}
  {{- end }}
  metrics:
    {{- if .autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .autoscaling.customMetrics }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
