{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-worker.fullname" . }}
  labels:
    {{- include "laravel-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laravel-worker.selectorLabels" . | nindent 4 }}
    laravel.com/pod-type: web
{{- end }}
